Repository purpleclay/nsv, pull requests merged in 2024-11, with the labels that each got.

#181 fix: nsv logger issue causes installation to fail (#180)
  cmd/root.go
Labels: size/XS

#185 ci: extend goreleaser configuration to publish to nix nur
  .goreleaser.yaml
Labels: size/S

#186 chore: include support for running nsv using nix
  .gitignore
  default.nix
  docs/install/binary.md
  docs/running/dagger.md
  docs/running/docker.md
  docs/running/nix.md
  flake.nix
  mkdocs.yml
Labels: size/L

#187 chore: ensure nix build produces a static derivation that doesn't compromise the hash
  default.nix
Labels: size/S
