Repository purpleclay/nsv, pull requests merged in 2024-12, with the labels that each got.

#190 fix: add support for detecting and repairing a shallow clone of a repository
  .github/workflows/nsv.yml
  .github/workflows/shellcheck.yml
  cmd/next.go
  cmd/patch.go
  cmd/root.go
  cmd/tag.go
  docs/git-repair.md
  go.mod
  go.sum
  internal/nsv/repository.go
  internal/nsv/repository_test.go
  internal/nsv/semver.go
  mkdocs.yml
Labels: size/L

#183 chore: update stdout for install script
  scripts/install
Labels: size/L

#193 chore: rename install script and update documentation
  .github/workflows/shellcheck.yml
  docs/install/binary.md
  flake.lock
  flake.nix
  scripts/install.sh
Labels: size/S

#195 fix: hook scripts should execute inside and outside a monorepo without being context aware
  cmd/patch_test.go
  cmd/root.go
  cmd/tag_test.go
  go.mod
  go.sum
  internal/nsv/semver.go
  internal/nsv/semver_test.go
  internal/tui/summary.go
  taskfile.yaml
Labels: size/M

#198 ci: update goreleaser workflow to ensure nix is installed ready to pu…
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: size/XS

#200 ci: add a workflow to patch the default.nix file on release
  .github/workflows/nix-patch.yml
Labels: size/M

#202 feat: automatically load environment variables if a dotenv file is detected within the project root
  go.mod
  go.sum
  main.go
Labels: size/XS

#204 docs: add a section to the documentation about setting options
  docs/git-repair.md
  docs/install/binary.md
  docs/options.md
  docs/patch-files.md
  docs/reference/cli/nsv-next.md
  docs/reference/cli/nsv-patch.md
  docs/reference/cli/nsv-tag.md
  docs/reference/cli/nsv.md
  docs/reference/env-vars.md
  docs/running/dagger.md
  docs/running/nix.md
  mkdocs.yml
  taskfile.yaml
Labels: size/M

#205 fix(deps): upgrade version of go to 1.23.4
  flake.lock
  go.mod
Labels: size/S

#207 ci: fix broken nix patch workflow due to go upgrade
  .github/workflows/nix-patch.yml
  default.nix
Labels: size/S

#208 docs(README): add Arch Linux installation instructions
  docs/install/binary.md
Labels: size/XS

#210 fix: a patched commit should skip by default
  cmd/patch.go
  cmd/patch_test.go
Labels: size/XS

#212 docs: the default commit when patching files will now skip any subsequent build
  docs/patch-files.md
  docs/reference/cli/nsv-patch.md
Labels: size/S

#216 fix: add missing bash interpreter to nsv docker image
  Dockerfile
Labels: size/XS
